### ISSUE TITLE
error in console

### ISSUE THREAD

**Issue by Xuefeng-Zhu** [kfichter/qmix-revamp#1]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/qtum-project/Lobby)
```

**Current behavior**

![image](https://user-images.githubusercontent.com/5875315/36625873-a6d88d3a-18ed-11e8-9451-9d078e9594ca.png)

**Expected behavior**

There is no error, and the app works fine

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

In chrome browser

**Comment by kfichter** [comment]
Thanks! I've been able to reproduce this. The issue occurs because the app tries to compile when you don't have a selected file. Here's the offending function:
https://github.com/kfichter/qmix-revamp/blob/028d4dfa922d7724a6f1c9945a0e9f24285941f2/src/client/app/shared/components/sidebar/compile-tab/compile-tab.component.ts#L43-L56

Specifically, `selectedFile` is `undefined`, so `selectedFile.name` will throw an error. I'd be happy to accept a pull request on this issue!

**Comment by Xuefeng-Zhu** [comment]
@kfichter Cool. Thank you for the quick response. I will try to fix it.

**Comment by Xuefeng-Zhu** [comment]
@kfichter fix in https://github.com/kfichter/qmix-revamp/pull/2
